"""create initial schema

Revision ID: 09aaba0e3a3e
Revises: 
Create Date: 2026-09-14 13:37:33.058224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09aaba0e3a3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('successful_documents', sa.Integer(), nullable=False),
    sa.Column('failed_documents', sa.Integer(), nullable=False),
    sa.Column('review_documents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('failed_documents >= 0', name='ck_jobs_failed_documents_non_negative'),
    sa.CheckConstraint('processed_documents >= 0', name='ck_jobs_processed_documents_non_negative'),
    sa.CheckConstraint('review_documents >= 0', name='ck_jobs_review_documents_non_negative'),
    sa.CheckConstraint('successful_documents >= 0', name='ck_jobs_successful_documents_non_negative'),
    sa.CheckConstraint('total_documents >= 0', name='ck_jobs_total_documents_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_documents_attempt_count_non_negative'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_documents_size_bytes_non_negative'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_job_content_hash', 'documents', ['job_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('output_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_job_id'), 'exports', ['job_id'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('processing_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='ck_extractions_attempt_number_positive'),
    sa.CheckConstraint('processing_latency_ms IS NULL OR processing_latency_ms >= 0', name='ck_extractions_latency_non_negative'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_extractions_status'), 'extractions', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_document_id'), 'leads', ['document_id'], unique=False)
    op.create_index(op.f('ix_leads_extraction_id'), 'leads', ['extraction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_extraction_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_document_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_extractions_status'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_job_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_index('ix_documents_job_content_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
