"""enforce document idempotency

Revision ID: e596e0b85ab8
Revises: 09aaba0e3a3e
Create Date: 2026-09-15 05:19:27.941112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e596e0b85ab8'
down_revision: Union[str, Sequence[str], None] = '09aaba0e3a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_job_content_hash'), table_name='documents')
    op.create_index('uq_documents_job_content_hash', 'documents', ['job_id', 'content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_documents_job_content_hash', table_name='documents')
    op.create_index(op.f('ix_documents_job_content_hash'), 'documents', ['job_id', 'content_hash'], unique=False)
    # ### end Alembic commands ###
